[package]
name = "corex-cache"
description = "Conditional metadata and archive cache for CorexPM"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
corex-errors = { path = "../corex-errors" }
corex-config = { path = "../corex-config" }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
