[package]
name = "corex-graph"
description = "Compact resolved dependency graph for CorexPM"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
corex-errors = { path = "../corex-errors" }
corex-manifest = { path = "../corex-manifest" }
corex-semver = { path = "../corex-semver" }
serde = { workspace = true }


[lints]
workspace = true
