[package]
name = "corex-linker"
description = "Isolated node_modules tree materialization and package binary linker for CorexPM"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
corex-errors = { path = "../corex-errors" }
corex-graph = { path = "../corex-graph" }
corex-store = { path = "../corex-store" }
corex-manifest = { path = "../corex-manifest" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
corex-config = { path = "../corex-config" }
corex-registry = { path = "../corex-registry" }
corex-resolver = { path = "../corex-resolver" }

[lints]
workspace = true
